[package]
name = "binsearch-rust"
version = "0.1.0"
authors = ["Avinash Sridhar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"